name: "Entra: Create Emergency Access Accounts"

on:
  ## This suppression will be removed once branch-driven Workflows have been completed
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: choice
        description: Environment to deploy to
        options:
          - sumvita-gov
          - kalvico-gov
          - sumvita
          - kalvico
      ## Drift detection not supported as this is a one-time execution
      # execute:
      #   required: true
      #   type: boolean
      #   description: Execute change
      #   default: false

permissions:
  id-token: write
  contents: read
  pull-requests: write

env:
  AZURE_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
  AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  AZURE_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
  IS_AZURE_GOV: "${{ vars.IS_AZURE_GOV }}"
  ExecuteChange: "${{ inputs.execute || 'false'}}"

  DomainName: ${{ vars.ONMICROSOFT_DOMAIN_NAME }}
  BreakglassUserCount: 2
  VaultName: ${{ vars.EMERGENCY_ACCOUNTS_KEYVAULT_NAME }}
  PasswordLength: 24
  DisplayName: ezdcloud.admin

jobs:
  run-powershell-script:
    environment: ${{ inputs.environment }}
    name: "Implement Authentication Methods"
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: 'EasyDynamics/EntraID-800-53-Terraform-Modules'
          ref: '0.0.111'
          sparse-checkout: 'powershell-modules/EZD.ECI.EmergencyAccounts'
          ssh-key: ${{ secrets.MODULES_REPO_SSH_PRIVATE_KEY }}
      
      - name: Checkout common module
        uses: actions/checkout@v4
        with:
          repository: 'EasyDynamics/EntraID-800-53-Terraform-Modules'
          ref: '0.0.115'
          path: 'EZD.ECI.Common'
          sparse-checkout: 'powershell-modules/EZD.ECI.Common'
          ssh-key: ${{ secrets.MODULES_REPO_SSH_PRIVATE_KEY }}

      - name: Configure Authentication Method Policies
        shell: pwsh
        run: |
          $ErrorActionPreference = "Continue" #"Stop"
          Import-Module .\EZD.ECI.Common\powershell-modules\EZD.ECI.Common\EZD.ECI.Common.psd1 -Force
          Connect-EciGraph

          ## Re-emit env vars in PowerShell conventional variables
          $StrippedDisplayName = $env:DisplayName -replace '\s',''
          
          $LogPath = New-Item -ItemType Directory -Path local-exec-logs -Force
      
      
          Install-Module Az.Accounts -RequiredVersion 3.0.1 -Force 
          Install-Module Az.KeyVault -RequiredVersion 6.0.1 -Force 
      
          Import-Module .\powershell-modules\EZD.ECI.EmergencyAccounts\EZD.ECI.EmergencyAccounts.psd1 -Force

          $count = 1
          while ($count -le $env:BreakglassUserCount) {
            Write-Output "In loop, iteration # $count"
            $UserPrincipalName = $StrippedDisplayName + $count + "@" + $env:DomainName
            Set-Location $LogPath
            New-EmergencyAccounts -UserPrincipalName $UserPrincipalName -DisplayName $($env:DisplayName+"."+$count) -VaultName $env:VaultName -KeyVaultSecretName "Emergency-Account-$($count)" 2>&1
            if ($status -eq 1) {
              break
            }
            $count++
          }