name: "GCP: Get User Password Policies" 

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - '.github/workflows/ps-gcp-get-userpasswordpolicies.yml'
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: choice
        description: Environment to deploy to
        options:
          - kalvico-gcp
permissions:
  id-token: write
  contents: read

env:
  GCP_SERVICE_ACCOUNT_CLIENT_ID: ${{ vars.GCP_SERVICE_ACCOUNT_CLIENT_ID }}
  GCP_SERVICE_ACCOUNT_SUBJECT_EMAIL: ${{ vars.GCP_SERVICE_ACCOUNT_SUBJECT_EMAIL }}
  GCP_SERVICE_ACCOUNT_EMAIL: ${{ vars.GCP_SERVICE_ACCOUNT_EMAIL }}
  GCP_SERVICE_ACCOUNT_CREDENTIALS_P12_BASE64: ${{ secrets.GCP_SERVICE_ACCOUNT_CREDENTIALS_P12_BASE64 }}
  GCP_SERVICE_ACCOUNT_CREDENTIALS_P12_PASSWORD: ${{ secrets.GCP_SERVICE_ACCOUNT_CREDENTIALS_P12_PASSWORD }}
  
  GCP_PASSWORD_STRENGTH_ENFORCED: ${{ vars.GCP_PASSWORD_STRENGTH_ENFORCED }}
  GCP_MINIMUM_PASSWORD_LENGTH: ${{ vars.GCP_MINIMUM_PASSWORD_LENGTH }}
  GCP_MAXIMUM_PASSWORD_LENGTH: ${{ vars.GCP_MAXIMUM_PASSWORD_LENGTH }}
  GCP_ENFORCE_NEXT_SIGN_IN: ${{ vars.GCP_ENFORCE_NEXT_SIGN_IN }}
  GCP_PASSWORD_REUSE_ALLOWED: ${{ vars.GCP_PASSWORD_REUSE_ALLOWED }}
  GCP_PASSWORD_EXPIRATION_DAYS: ${{ vars.GCP_PASSWORD_EXPIRATION_DAYS }}

jobs: 
  alert-upon-prod-deployment:
    if: ${{ inputs.environment == 'PROD' }}
    uses: ./.github/workflows/prod-deployment-alerts.yml
    with:
      environment: ${{ inputs.environment || 'kalvico-gcp' }}
    secrets: inherit

  gcp-get-user-password-policies:
    environment: ${{ inputs.environment || 'kalvico-gcp' }}
    runs-on: ubuntu-latest
    steps:

    # Checkout the repository to the GitHub Actions runner
    - name: Checkout common module
      uses: actions/checkout@v4
      with:
        repository: 'EasyDynamics/eci-gcp-modules'
        ref: '0.0.7'
        path: 'EZD.ECI.GCP.Common'
        sparse-checkout: 'EZD.ECI.GCP.Common'
        ssh-key: ${{ secrets.GCP_MODULES_REPO_SSH_PRIVATE_KEY }}

    - name: Checkout feature module
      uses: actions/checkout@v4
      with:
        repository: 'EasyDynamics/eci-gcp-modules'
        ref: '0.0.7'
        path: 'EZD.ECI.GCP.UserPasswordPolicies'
        sparse-checkout: 'EZD.ECI.GCP.UserPasswordPolicies'
        ssh-key: ${{ secrets.GCP_MODULES_REPO_SSH_PRIVATE_KEY }}

    - name: 'Get User Password Policies'
      shell: pwsh
      run: |-
        Import-Module .\EZD.ECI.GCP.Common\EZD.ECI.GCP.Common\EZD.ECI.GCP.Common.psd1 -Force
        Import-Module .\EZD.ECI.GCP.UserPasswordPolicies\EZD.ECI.GCP.UserPasswordPolicies\EZD.ECI.GCP.UserPasswordPolicies.psd1 -Force

        $Scopes = @("https://www.googleapis.com/auth/cloud-identity.policies.readonly")

        $AccessTokenSplat = @{
          Issuer = $env:GCP_SERVICE_ACCOUNT_EMAIL
          Subject = $env:GCP_SERVICE_ACCOUNT_SUBJECT_EMAIL
          P12CertificateBase64 = $env:GCP_SERVICE_ACCOUNT_CREDENTIALS_P12_BASE64
          P12CertificatePassword = $env:GCP_SERVICE_ACCOUNT_CREDENTIALS_P12_PASSWORD
          Scopes = $Scopes
        }

        $AccessToken = Get-EciGwsAccessToken @AccessTokenSplat

        $DesiredPasswordStrengthEnforced = [System.Convert]::ToBoolean($env:GCP_PASSWORD_STRENGTH_ENFORCED)
        $DesiredEnforceNextSignIn = [System.Convert]::ToBoolean($env:GCP_ENFORCE_NEXT_SIGN_IN)
        $DesiredPasswordReuseAllowed = [System.Convert]::ToBoolean($env:GCP_PASSWORD_REUSE_ALLOWED)

        Get-UserPasswordPolicy -DesiredPasswordStrengthEnforced $DesiredPasswordStrengthEnforced -DesiredMinLength $env:GCP_MINIMUM_PASSWORD_LENGTH -DesiredMaxLength $env:GCP_MAXIMUM_PASSWORD_LENGTH -DesiredEnforceNextSignIn $DesiredEnforceNextSignIn -DesiredPasswordReuseAllowed $DesiredPasswordReuseAllowed -DesiredPasswordExpirationDays $env:GCP_PASSWORD_EXPIRATION_DAYS -accessToken $AccessToken
