name: "Entra: Set Enterprise App User Consent Setting"

on: 
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - '.github/workflows/ps-set-enterprise-app-user-consent-setting.yml'
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: choice
        description: Environment to deploy to
        options:
          - sumvita-gov
          - kalvico-gov
          - sumvita
          - kalvico
      execute:
        required: true
        type: boolean
        description: Execute change
        default: false

permissions:
  id-token: write
  contents: read
  pull-requests: write

env:
  AZURE_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
  AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  AZURE_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
  IS_AZURE_GOV: "${{ vars.IS_AZURE_GOV }}"
  ExecuteChange: "${{ inputs.execute || 'false'}}"

  ENT_APP_DEFAULT_CONSENT_PERMISSIONS: ${{ vars.ENT_APP_DEFAULT_CONSENT_PERMISSIONS }}
  
jobs: 
  alert-upon-prod-deployment:
    if: ${{ inputs.environment == 'PROD' }}
    uses: ./.github/workflows/prod-deployment-alerts.yml
    with:
      environment: ${{ inputs.environment || vars.MANAGEMENT_TENANT_NAME_GOV }}
    secrets: inherit

  run-powershell-script:
    environment: ${{ inputs.environment || vars.MANAGEMENT_TENANT_NAME_GOV }}
    name: "Configure Enterprise App Enterprise App User Consent Setting"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout feature module
        uses: actions/checkout@v4
        with:
          repository: 'EasyDynamics/EntraID-800-53-Terraform-Modules'
          ref: '0.0.109'
          path: 'EZD.ECI.PolicyAuthorizationPolicy'
          sparse-checkout: 'powershell-modules/EZD.ECI.PolicyAuthorizationPolicy'
          ssh-key: ${{ secrets.MODULES_REPO_SSH_PRIVATE_KEY }}

      - name: Checkout common module
        uses: actions/checkout@v4
        with:
          repository: 'EasyDynamics/EntraID-800-53-Terraform-Modules'
          ref: '0.0.115'
          path: 'EZD.ECI.Common'
          sparse-checkout: 'powershell-modules/EZD.ECI.Common'
          ssh-key: ${{ secrets.MODULES_REPO_SSH_PRIVATE_KEY }}

      - name: Authenticate and Configure Enterprise App User Consent Permissions
        shell: pwsh
        run: |
          # Install and import modules
          Import-Module .\EZD.ECI.Common\powershell-modules\EZD.ECI.Common\EZD.ECI.Common.psd1 -Force
          Connect-EciGraph

          Import-Module .\EZD.ECI.PolicyAuthorizationPolicy\powershell-modules\EZD.ECI.PolicyAuthorizationPolicy\EZD.ECI.PolicyAuthorizationPolicy.psd1 -Force
        
          ## Must cast into booleans since GitHub Actions passes inputs explicitly as a string.
          ## This is the behavior regardless if they are labeled as boolean workflow inputs.
          $ExecuteChange = [System.Convert]::ToBoolean($env:ExecuteChange)
          
          # Configure enterprise app Enterprise App User Consent Setting
          Set-EnterpriseAppUserConsentSetting -DesiredConsentSetting $env:ENT_APP_DEFAULT_CONSENT_PERMISSIONS -ExecuteChange:$ExecuteChange