name: "Entra: Set PIM Role Settings"

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
     - '.github/workflows/ps-set-pim-settings.yml'
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: choice
        description: Environment to deploy to
        options:
          - sumvita-gov
          - sumvita
          - kalvico
      execute:
        required: true
        type: boolean
        description: Execute Change
        default: false

permissions:
  id-token: write
  contents: read
  pull-requests: write

env:
  AZURE_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
  AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  AZURE_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
  IS_AZURE_GOV: ${{ vars.IS_AZURE_GOV }}
  PIM_APPROVAL_REQUIRED: ${{ vars.PIM_APPROVAL_REQUIRED }}
  PIM_ADDITIONAL_NOTIFICATION_RECIPIENTS: ${{ vars.PIM_ADDITIONAL_NOTIFICATION_RECIPIENTS }}
  ExecuteChange: "${{ inputs.execute || 'false'}}"


jobs:
  run-powershell-script:
    environment: ${{ inputs.environment || vars.MANAGEMENT_TENANT_NAME_GOV }}
    name: "Set PIM Settings"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PIM Settings module
        uses: actions/checkout@v4
        with:
          repository: 'EasyDynamics/EntraID-800-53-Terraform-Modules'
          ref: '0.0.132'
          path: 'EZD.ECI.PIMSettings'
          sparse-checkout: 'powershell-modules/EZD.ECI.PIMSettings'
          ssh-key: ${{ secrets.MODULES_REPO_SSH_PRIVATE_KEY }}

      - name: Checkout common module
        uses: actions/checkout@v4
        with:
          repository: 'EasyDynamics/EntraID-800-53-Terraform-Modules'
          ref: '0.0.132'
          path: 'EZD.ECI.Common'
          sparse-checkout: 'powershell-modules/EZD.ECI.Common'
          ssh-key: ${{ secrets.MODULES_REPO_SSH_PRIVATE_KEY }}

      - name: Authenticate and Configure PIM Settings for Highly Privileged Roles
        shell: pwsh
        run: |
          # Install and import modules
          Install-Module -Name "Microsoft.Graph.Identity.SignIns" -Force
          Import-Module .\EZD.ECI.Common\powershell-modules\EZD.ECI.Common\EZD.ECI.Common.psd1 -Force
          Connect-EciGraph

          Import-Module .\EZD.ECI.PIMSettings\powershell-modules\EZD.ECI.PIMSettings\EZD.ECI.PIMSettings.psd1 -Force

          ## Must cast into booleans since GitHub Actions passes inputs explicitly as a string.
          ## This is the behavior regardless if they are labeled as boolean workflow inputs.
          $ExecuteChange = [System.Convert]::ToBoolean($env:ExecuteChange)

          ## Convert Approval and Default Recipient Settings To Boolean
          $ApprovalAndDefaultRecipientSettings = [System.Convert]::ToBoolean($env:PIM_APPROVAL_REQUIRED)

          # Convert comma-separated string to array (if not empty) and Inteprete None as empty array
          $NotificationRecipientsNotSet = (-Not $env:PIM_ADDITIONAL_NOTIFICATION_RECIPIENTS) `
                                          -or (($env:PIM_ADDITIONAL_NOTIFICATION_RECIPIENTS).ToLower() -eq 'none') `
                                          -or ($env:PIM_ADDITIONAL_NOTIFICATION_RECIPIENTS -eq '')
          if ($NotificationRecipientsNotSet) { 
              $AdditionalRecipients = @() 
          } else { 
              $AdditionalRecipients = $env:PIM_ADDITIONAL_NOTIFICATION_RECIPIENTS.Split(',').Trim() 
          }

          # Set the PIM settings
          Set-PIMSettings -PIM_APPROVAL_REQUIRED $ApprovalAndDefaultRecipientSettings -AdditionalNotificationRecipients $AdditionalRecipients -ExecuteChange $ExecuteChange 

