name: "Entra: Set Cross Tenant Access Setting Defaults (B2B)"

on: 
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - '.github/workflows/ps-set-cross-tenant-access-setting-defaults-b2b.yml'
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: choice
        description: Environment to deploy to
        options:
          - sumvita-gov
          - kalvico-gov
          - sumvita
          - kalvico
      execute:
        required: true
        type: boolean
        description: Execute change
        default: false
  ## When we create the nightly drift detection PR, we will need to subsequently add
  ## `worfklow_call` to each workflow so they may be called in one parent workflow

permissions:
  id-token: write
  contents: read
  pull-requests: write

env:
  AZURE_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
  AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  AZURE_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
  IS_AZURE_GOV: "${{ vars.IS_AZURE_GOV }}"
  ExecuteChange: "${{ inputs.execute || 'false'}}"

jobs: 
  alert-upon-prod-deployment:
    if: ${{ inputs.environment == 'PROD' }}
    uses: ./.github/workflows/prod-deployment-alerts.yml
    with:
      environment: ${{ inputs.environment || vars.MANAGEMENT_TENANT_NAME_GOV }}
    secrets: inherit

  run-powershell-script:
    environment: ${{ inputs.environment || vars.MANAGEMENT_TENANT_NAME_GOV }}
    name: "Configure Default Entra B2B Cross Tenant Access Settings"
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout feature module
        uses: actions/checkout@v4
        with:
          repository: 'EasyDynamics/EntraID-800-53-Terraform-Modules'
          ref: '0.0.116'
          ssh-key: ${{ secrets.MODULES_REPO_SSH_PRIVATE_KEY }}
      
      - name: Checkout common module
        uses: actions/checkout@v4
        with:
          repository: 'EasyDynamics/EntraID-800-53-Terraform-Modules'
          ref: '0.0.115'
          path: 'EZD.ECI.Common'
          sparse-checkout: 'powershell-modules/EZD.ECI.Common'
          ssh-key: ${{ secrets.MODULES_REPO_SSH_PRIVATE_KEY }}
          
      - name: Authenticate and Configure Default Entra B2B Cross Tenant Access Settings
        shell: pwsh
        run: |
          # Install and import modules
          Import-Module .\EZD.ECI.Common\powershell-modules\EZD.ECI.Common\EZD.ECI.Common.psd1 -Force
          
          Connect-EciGraph
          Import-Module .\powershell-modules\EZD.ECI.CrossTenantAccess\EZD.ECI.CrossTenantAccess.psd1 -Force

          ## Must cast into booleans since GitHub Actions passes inputs explicitly as a string.
          ## This is the behavior regardless if they are labeled as boolean workflow inputs.
          $ExecuteChange = [System.Convert]::ToBoolean($env:ExecuteChange)
          
          Set-CrossTenantAccessSettingDefaults -BlockAll $true -ExecuteChange:$ExecuteChange