name: "Entra: Set Default User Role"

on: 
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - '.github/workflows/ps-set-default-user-role.yml'
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: choice
        description: Environment to deploy to
        options:
          - sumvita-gov
          - kalvico-gov
          - sumvita
          - kalvico
      execute:
        required: true
        type: boolean
        description: Execute change
        default: false

permissions:
  id-token: write
  contents: read
  pull-requests: write

env:
  AZURE_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
  AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  AZURE_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
  IS_AZURE_GOV: "${{ vars.IS_AZURE_GOV }}"
  ExecuteChange: "${{ inputs.execute || 'false'}}"

  ALLOW_NONPRIV_SECURITY_GROUP_CREATION: ${{ vars.ALLOW_NONPRIV_SECURITY_GROUP_CREATION }}
  ALLOW_NONPRIV_B2C_TENANT_CREATION: ${{ vars.ALLOW_NONPRIV_B2C_TENANT_CREATION }}
  ALLOW_NONPRIV_ENTERPRISE_APP_CREATION: ${{ vars.ALLOW_NONPRIV_ENTERPRISE_APP_CREATION }}

jobs: 
  alert-upon-prod-deployment:
    if: ${{ inputs.environment == 'PROD' }}
    uses: ./.github/workflows/prod-deployment-alerts.yml
    with:
      environment: ${{ inputs.environment || vars.MANAGEMENT_TENANT_NAME_GOV }}
    secrets: inherit

  run-powershell-script:
    environment: ${{ inputs.environment || vars.MANAGEMENT_TENANT_NAME_GOV }}
    name: "Configure Default User Role"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout feature module
        uses: actions/checkout@v4
        with:
          repository: 'EasyDynamics/EntraID-800-53-Terraform-Modules'
          ref: '0.0.113'
          path: 'EZD.ECI.PolicyAuthorizationPolicy'
          sparse-checkout: 'powershell-modules/EZD.ECI.PolicyAuthorizationPolicy'
          ssh-key: ${{ secrets.MODULES_REPO_SSH_PRIVATE_KEY }}

      - name: Checkout common module
        uses: actions/checkout@v4
        with:
          repository: 'EasyDynamics/EntraID-800-53-Terraform-Modules'
          ref: '0.0.115'
          path: 'EZD.ECI.Common'
          sparse-checkout: 'powershell-modules/EZD.ECI.Common'
          ssh-key: ${{ secrets.MODULES_REPO_SSH_PRIVATE_KEY }}

      - name: Authenticate and Configure Default User Role
        shell: pwsh
        run: |
          # Install and import modules
          Import-Module .\EZD.ECI.Common\powershell-modules\EZD.ECI.Common\EZD.ECI.Common.psd1 -Force
          Connect-EciGraph

          Import-Module .\EZD.ECI.PolicyAuthorizationPolicy\powershell-modules\EZD.ECI.PolicyAuthorizationPolicy\EZD.ECI.PolicyAuthorizationPolicy.psd1 -Force
          
          ## Must cast into booleans since input values are passed explicitly as a string.
          ## This is the behavior regardless if they are labeled as boolean workflow inputs.
          $ExecuteChange = [System.Convert]::ToBoolean($env:ExecuteChange)
          $DefaultUserRolePermissions = @{
            AllowedToCreateSecurityGroups = [System.Convert]::ToBoolean($env:ALLOW_NONPRIV_SECURITY_GROUP_CREATION)
            AllowedToCreateTenants = [System.Convert]::ToBoolean($env:ALLOW_NONPRIV_B2C_TENANT_CREATION)
            AllowedToCreateApps = [System.Convert]::ToBoolean($env:ALLOW_NONPRIV_ENTERPRISE_APP_CREATION)
          }
          
          # Configure default user rule permissions
          Set-DefaultUserRole -DefaultUserRolePermissions $DefaultUserRolePermissions -ExecuteChange:$ExecuteChange

