name: "Entra: Set Password Expiration Policies"

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - '.github/workflows/ps-set-password-expiration-policy.yml'
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: choice
        description: Environment to deploy to
        options:
          - sumvita-gov
          - kalvico-gov
          - sumvita
          - kalvico
      execute:
        required: true
        type: boolean
        description: Execute Change
        default: false

permissions:
  id-token: write
  contents: read
  pull-requests: write

env:
  AZURE_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
  AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  AZURE_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
  IS_AZURE_GOV: ${{ vars.IS_AZURE_GOV }}
  ExecuteChange: "${{ inputs.execute || 'false'}}"

  PASSWORD_EXPIRATION_PERIOD: ${{ vars.PASSWORD_EXPIRATION_PERIOD }}

jobs:
  alert-upon-prod-deployment:
    if: ${{ inputs.environment == 'PROD' }}
    uses: ./.github/workflows/prod-deployment-alerts.yml
    with:
      environment: ${{ inputs.environment || vars.MANAGEMENT_TENANT_NAME_GOV }}
    secrets: inherit

  run-powershell-script:
    environment: ${{ inputs.environment || vars.MANAGEMENT_TENANT_NAME_GOV }}
    name: "Set Password Expiration Policy"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PasswordPolicy module
        uses: actions/checkout@v4
        with:
          repository: 'EasyDynamics/EntraID-800-53-Terraform-Modules'
          ref: '0.0.130'
          path: 'EZD.ECI.UserPasswordExpiration'
          sparse-checkout: 'powershell-modules/EZD.ECI.PasswordPolicy'
          ssh-key: ${{ secrets.MODULES_REPO_SSH_PRIVATE_KEY }}

      - name: Checkout common module
        uses: actions/checkout@v4
        with:
          repository: 'EasyDynamics/EntraID-800-53-Terraform-Modules'
          ref: '0.0.122'
          path: 'EZD.ECI.Common'
          sparse-checkout: 'powershell-modules/EZD.ECI.Common'
          ssh-key: ${{ secrets.MODULES_REPO_SSH_PRIVATE_KEY }}

      - name: Authenticate and Configure Password Expiration Policy For Tenant
        shell: pwsh
        run: |
          # Install and import modules
          Install-Module -Name "Microsoft.Graph.Identity.DirectoryManagement" -Force
          Import-Module .\EZD.ECI.Common\powershell-modules\EZD.ECI.Common\EZD.ECI.Common.psd1 -Force
          Connect-EciGraph

          Import-Module .\EZD.ECI.UserPasswordExpiration\powershell-modules\EZD.ECI.PasswordPolicy\EZD.ECI.PasswordPolicy.psd1 -Force

          ## Must cast into booleans since GitHub Actions passes inputs explicitly as a string.
          ## This is the behavior regardless if they are labeled as boolean workflow inputs.
          $ExecuteChange = [System.Convert]::ToBoolean($env:ExecuteChange)

          # Set the password expiration policy
          Set-PasswordPolicy -PasswordValidityPeriodInDays $env:PASSWORD_EXPIRATION_PERIOD -PasswordNotificationWindowInDays $env:PASSWORD_NOTIFICATION_WINDOW_IN_DAYS -ExecuteChange:$ExecuteChange