name: "Entra: Set External Collaboration Settings (B2B)" 

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - '.github/workflows/ps-set-external-collab-settings.yml'
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: choice
        description: Environment to deploy to
        options:
          - sumvita-gov
          - kalvico-gov
          - sumvita
          - kalvico
      execute:
        required: true
        type: boolean
        description: Execute change
        default: false

permissions:
  id-token: write
  contents: read
  pull-requests: write

env:
  AZURE_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
  AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  AZURE_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
  IS_AZURE_GOV: "${{ vars.IS_AZURE_GOV }}"
  ExecuteChange: "${{ inputs.execute || 'false'}}"

  GUEST_USER_ROLE_ID: "${{ vars.GUEST_USER_ROLE_ID }}"
  GUEST_INVITER_RESTRICTIONS: "${{ vars.GUEST_INVITER_RESTRICTIONS }}"
  ALLOW_GUEST_SELF_SERVICE_SIGNUP: "${{ vars.ALLOW_GUEST_SELF_SERVICE_SIGNUP }}"
  ALLOW_GUEST_SELF_SERVICE_LEAVE: "${{ vars.ALLOW_GUEST_SELF_SERVICE_LEAVE }}"

jobs: 
  alert-upon-prod-deployment:
    if: ${{ inputs.environment == 'PROD' }}
    uses: ./.github/workflows/prod-deployment-alerts.yml
    with:
      environment: ${{ inputs.environment || vars.MANAGEMENT_TENANT_NAME_GOV }}
    secrets: inherit

  run-powershell-script:
    environment: ${{ inputs.environment || vars.MANAGEMENT_TENANT_NAME_GOV }}
    name: "Configure B2B External Collaboration Settings"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout feature module
        uses: actions/checkout@v4
        with:
          repository: 'EasyDynamics/EntraID-800-53-Terraform-Modules'
          ref: '0.0.119'
          path: 'EZD.ECI.GuestDefaults'
          sparse-checkout: 'powershell-modules/EZD.ECI.GuestDefaults'
          ssh-key: ${{ secrets.MODULES_REPO_SSH_PRIVATE_KEY }}

      - name: Checkout common module
        uses: actions/checkout@v4
        with:
          repository: 'EasyDynamics/EntraID-800-53-Terraform-Modules'
          ref: '0.0.115'
          path: 'EZD.ECI.Common'
          sparse-checkout: 'powershell-modules/EZD.ECI.Common'
          ssh-key: ${{ secrets.MODULES_REPO_SSH_PRIVATE_KEY }}

      - name: Set External Collaboration Settings
        shell: pwsh
        run: |
          # Install and import modules
          Install-Module -Name Microsoft.Graph.Identity.SignIns -RequiredVersion 2.24.0 -Force
          Install-Module -Name Microsoft.Graph.Beta.Identity.SignIns -RequiredVersion 2.24.0 -Force
          Install-Module -Name Microsoft.Graph.Identity.DirectoryManagement -RequiredVersion 2.24.0 -Force
          Install-Module -Name Microsoft.Graph.Beta.Identity.DirectoryManagement -RequiredVersion 2.24.0 -Force

          Import-Module .\EZD.ECI.Common\powershell-modules\EZD.ECI.Common\EZD.ECI.Common.psd1 -Force
          Connect-EciGraph

          Import-Module .\EZD.ECI.GuestDefaults\powershell-modules\EZD.ECI.GuestDefaults\EZD.ECI.GuestDefaults.psd1 -Force

          # Define variables
          $GuestUserRoleIdGuid = $env:GUEST_USER_ROLE_ID
          $AllowInvitesFrom = $env:GUEST_INVITER_RESTRICTIONS
          $ExecuteChange = [System.Convert]::ToBoolean($env:ExecuteChange)

          # Configure external collaboration settings
          Write-Output "Initiating external collaboration settings configuration."
          Set-GuestDefaults -GuestUserRoleIdGuid $GuestUserRoleIdGuid -AllowInvitesFrom $AllowInvitesFrom -ExecuteChange:$ExecuteChange